export const AI_ASSISTANT_NAME = "NEXUS AI";
export const AI_ASSISTANT_CHAT_LABEL = `${AI_ASSISTANT_NAME} Chat`;
export const AI_ASSISTANT_CHAT_CTA = `Opýtať sa ${AI_ASSISTANT_NAME}`;
export const AI_ASSISTANT_STATUS_ONLINE = `${AI_ASSISTANT_NAME} online`;
export const AI_ASSISTANT_STATUS_ACTIVE = `${AI_ASSISTANT_NAME} aktívna`;
