#!/usr/bin/env bash
# Cloud Agent start phase — per-boot runtime reconciliation.
# Brings up the Docker daemon and the local ephemeral Supabase stack, then writes
# apps/crm/.env.local so the Next.js dev server (terminals) can connect. Idempotent:
# safe to re-run; it detects already-running services.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRM_DIR="$REPO_ROOT/apps/crm"

echo "[start] Reconciling Docker daemon..."
# Nested-container networking: bridged container-to-container traffic must bypass
# the host iptables FORWARD chain, otherwise Supabase's inter-container calls hang.
sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true
if ! sudo docker info >/dev/null 2>&1; then
  sudo nohup dockerd --storage-driver=fuse-overlayfs >/tmp/dockerd.log 2>&1 &
  for i in $(seq 1 60); do
    sudo docker info >/dev/null 2>&1 && break
    [ "$i" -eq 60 ] && { echo "[start] ERROR: dockerd did not become ready"; tail -20 /tmp/dockerd.log; exit 1; }
    sleep 1
  done
fi
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true

echo "[start] Reconciling local Supabase stack..."
cd "$CRM_DIR"
if ! supabase status >/dev/null 2>&1; then
  supabase start
fi

echo "[start] Writing apps/crm/.env.local from local Supabase credentials..."
sb_env="$(supabase status -o env 2>/dev/null | sed 's/"//g' | grep -E '^[A-Z0-9_]+=')"
API_URL="$(printf '%s\n' "$sb_env" | grep '^API_URL=' | cut -d= -f2-)"
ANON_KEY="$(printf '%s\n' "$sb_env" | grep '^ANON_KEY=' | cut -d= -f2-)"
SERVICE_ROLE_KEY="$(printf '%s\n' "$sb_env" | grep '^SERVICE_ROLE_KEY=' | cut -d= -f2-)"
PUBLISHABLE_KEY="$(printf '%s\n' "$sb_env" | grep '^PUBLISHABLE_KEY=' | cut -d= -f2-)"

cat > "$CRM_DIR/.env.local" <<EOF
# Auto-generated by .cursor/start.sh — local ephemeral Supabase credentials.
# Do NOT commit. Real OpenAI/Stripe/Resend keys should be provided via secrets.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
TEST_SUPABASE_URL=${API_URL}
TEST_SUPABASE_ANON_KEY=${ANON_KEY}
TEST_SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
# Placeholders so runtime env validation (src/config/env.ts) passes locally.
OPENAI_API_KEY=${OPENAI_API_KEY:-sk-local-dev-placeholder}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_local_dev_placeholder}
CRON_SECRET=${CRON_SECRET:-local-dev-cron-secret}
NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3000
NEXT_PUBLIC_APP_URL=http://127.0.0.1:3000
EOF

echo "[start] Ready. Supabase API: ${API_URL} | Studio: http://127.0.0.1:54323"
