import { NextResponse } from "next/server";
import { isAuthorizedCronBearer } from "@/lib/cron-auth";
import { createAdminClient } from "@/lib/supabase/server";
import { hashedEmailRows } from "@/lib/meta/hash-email";

const META_API_BASE = "https://graph.facebook.com/v19.0";

export async function POST(request: Request) {
  // Internal admin tool — require CRON_SECRET bearer token
  if (!isAuthorizedCronBearer(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { source?: string };
  try { body = await request.json(); } catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }
  const source = body.source ?? "leads_demo";

  const accessToken = process.env.META_ACCESS_TOKEN;
  const adAccountId = process.env.META_AD_ACCOUNT_ID;

  // ─── Demo mode keď credentials nie sú nakonfigurované ─────────────────
  if (!accessToken || !adAccountId) {
    return NextResponse.json({
      audienceId:   "demo_aud_" + Date.now(),
      audienceName: "Revolis Predajcovia – Lookalike SK",
      size:         241 + Math.floor(Math.random() * 40),
      status:       "demo",
      message:      "Demo simulácia. Pre produkciu nastav META_ACCESS_TOKEN a META_AD_ACCOUNT_ID.",
    });
  }

  try {
    // 1. Načítaj emaily z leads_demo
    const supabase = createAdminClient();
    const { data: leads, error } = await supabase
      .from("leads_demo")
      .select("email")
      .limit(500);

    if (error || !leads?.length) {
      return NextResponse.json({ error: "Žiadne leady pre vytvorenie audience." }, { status: 400 });
    }

    const emailsPayload = hashedEmailRows(leads);
    if (emailsPayload.length === 0) {
      return NextResponse.json({ error: "Žiadne použiteľné e-maily pre audience." }, { status: 400 });
    }

    // 2. Vytvor Custom Audience na Meta
    const audienceName = `Revolis ${source} ${new Date().toISOString().slice(0, 10)}`;
    const caRes = await fetch(`${META_API_BASE}/act_${adAccountId}/customaudiences`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        access_token: accessToken,
        name: audienceName,
        description: "Generated by Revolis AI – Digital Twin module",
        subtype: "CUSTOM",
        customer_file_source: "USER_PROVIDED_ONLY",
      }),
    });

    const caData = await caRes.json() as { id?: string; error?: { message: string } };
    if (!caData.id) {
      throw new Error(caData.error?.message ?? "Meta API chyba pri vytváraní audience");
    }

    const audienceId = caData.id;

    // 3. Upload SHA-256 hashov normalizovaných e-mailov (nie čistých adries)
    const uploadRes = await fetch(`${META_API_BASE}/${audienceId}/users`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        access_token: accessToken,
        payload: {
          schema: ["EMAIL"],
          data: emailsPayload,
        },
      }),
    });

    const uploadData = await uploadRes.json() as { audience_id?: string; error?: { message: string } };
    if (uploadData.error) {
      throw new Error(uploadData.error.message);
    }

    // 4. Vytvor Lookalike Audience
    const laRes = await fetch(`${META_API_BASE}/act_${adAccountId}/customaudiences`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        access_token: accessToken,
        name: `${audienceName} – Lookalike 1%`,
        subtype: "LOOKALIKE",
        origin_audience_id: audienceId,
        lookalike_spec: JSON.stringify({
          ratio: 0.01,
          country: "SK",
          type: "similarity",
        }),
      }),
    });

    const laData = await laRes.json() as { id?: string; error?: { message: string } };

    return NextResponse.json({
      audienceId,
      audienceName,
      size: emailsPayload.length,
      status:     "creating",
      lookalikeId: laData.id ?? undefined,
      message:    `Custom Audience vytvorená z ${emailsPayload.length} emailov. Lookalike spracováva Meta (24–48h).`,
    });
  } catch (err) {
    console.error("[meta/lookalike]", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Neznáma chyba." },
      { status: 500 }
    );
  }
}
