-- BASELINE: the 30 tables that exist in PROD and that no migration creates.
--
-- Why this file exists
-- ===================
-- AP-023 (docs/reports/2026-09-25-schema-drift-inventory.md, #701) measured the
-- gap between production and this directory:
--
--   tables in PROD                              111
--   tables any migration creates                105
--   in PROD, created by no migration             30   <- this file
--   in a migration, absent from PROD             24   (NOT addressed here)
--
-- The consequence of the first number is that `supabase db reset`, a fresh
-- environment and a restore-from-backup all produce a database the application
-- cannot run on. AP-022 was the same gap showing up as a CI outage.
--
-- How it was produced, and what that costs
-- ========================================
-- NOT with `pg_dump --schema-only`. This session has read-only SQL access to
-- production through the Supabase MCP tool and no database connection string,
-- and asking for one would mean a production credential in a chat transcript.
-- So the DDL below is RECONSTRUCTED from the production catalogs:
--   pg_attribute / pg_attrdef      columns, types, defaults, NOT NULL
--   pg_constraint                  PK, UNIQUE, CHECK, FK
--   pg_indexes                     indexes not backing a constraint
--   pg_policies                    RLS policies
--   pg_trigger / pg_get_triggerdef triggers
--   pg_proc / pg_get_functiondef   the two functions those objects need
--
-- Reconstruction is weaker than pg_dump. Known to be out of scope here, and NOT
-- claimed to be covered: table/column COMMENTs, storage parameters, non-default
-- collations, table ACLs (GRANT), and anything outside the `public` schema. The
-- verification below is what is actually claimed, and no more.
--
-- Idempotent on purpose: every statement is IF NOT EXISTS or guarded. On
-- production, where all 30 tables already exist, this migration is a no-op. It
-- changes only what a clean database gets.

-- ---------------------------------------------------------------------------
-- 1. Functions the objects below depend on.
--    Neither is created by any migration -- the same drift, one level down.
--    `profile_agencies_for_auth()` is load-bearing for the whole tenant RLS
--    model and is referenced by policies across the schema, not only here.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.profile_agencies_for_auth()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select distinct p.agency_id
  from public.profiles p
  cross join lateral (
    select u.email::text as email from auth.users u where u.id = auth.uid()
  ) me
  where p.agency_id is not null
    and (
      p.auth_user_id = auth.uid()
      or p.id = auth.uid()
      or (
        me.email is not null
        and p.email is not null
        and lower(trim(both from p.email)) = lower(trim(both from me.email))
      )
    );
$function$;

CREATE OR REPLACE FUNCTION public.ai_triage_feedback_set_agency()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  select l.agency_id into new.agency_id
  from public.leads l
  where l.id = new.lead_id
  limit 1;
  return new;
end;
$function$;

-- ---------------------------------------------------------------------------
-- 2. Tables.
--    Foreign keys are deliberately NOT inline: they are applied in section 3
--    so the order of CREATE statements here cannot matter.
-- ---------------------------------------------------------------------------

-- The three tables below were created by hand through the Supabase Dashboard,
-- not by any deliberate schema design. Their column names are pasted fragments
-- of an AI tool's output. They are recorded here because they are production
-- reality and a baseline that omitted them would be a baseline that lies.
-- Their fate (and the personal data two of them hold) is the open question in
-- section C of docs/reports/2026-09-25-schema-drift-inventory.md. Recording
-- them is not endorsing them.
CREATE TABLE IF NOT EXISTS public."AI AGENT AUTOMAT ONBOARDING" (
  "<img src=""https://r2cdn.perplexity.ai/pplx-full-logo-primary-da" text
);

CREATE TABLE IF NOT EXISTS public."AI AGENT AUTOMAT ONBOARDING no.2.01" (
  "Názov stĺpca" text,
  "Typ dát" text,
  "Constraints" text,
  website_url text,
  phone text,
  region text,
  agent_count integer DEFAULT 0,
  source text,
  last_contacted_at timestamp with time zone,
  demo_clicked_at timestamp with time zone,
  lead_score integer DEFAULT 0,
  notes text
);

CREATE TABLE IF NOT EXISTS public."gpmmfashion@gmail.com tabulka" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "gpmmfashion@gmail.com tabulka_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_triage_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL,
  agency_id uuid,
  profile_id uuid NOT NULL,
  helpful boolean NOT NULL,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_triage_feedback_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_triage_run_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id text NOT NULL,
  source text NOT NULL DEFAULT 'cron_lead_ai_triage'::text,
  day_utc date NOT NULL,
  agency_id uuid,
  started_at timestamp with time zone NOT NULL,
  finished_at timestamp with time zone NOT NULL,
  duration_ms integer NOT NULL,
  outcome text NOT NULL,
  candidate_count integer NOT NULL DEFAULT 0,
  candidates_in_run_for_agency integer NOT NULL DEFAULT 0,
  claimed_for_agency integer NOT NULL DEFAULT 0,
  updated_for_agency integer NOT NULL DEFAULT 0,
  skipped_dupe_global integer NOT NULL DEFAULT 0,
  lock_acquired_insert integer NOT NULL DEFAULT 0,
  lock_acquired_after_failed integer NOT NULL DEFAULT 0,
  lock_stale_recovery integer NOT NULL DEFAULT 0,
  lock_skipped_completed integer NOT NULL DEFAULT 0,
  lock_skipped_lock_held integer NOT NULL DEFAULT 0,
  lock_skipped_race_or_missing integer NOT NULL DEFAULT 0,
  ai_api_fallback_leads integer NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_triage_run_metrics_outcome_ck CHECK ((outcome = ANY (ARRAY['success'::text, 'error'::text, 'no_claims'::text]))),
  CONSTRAINT ai_triage_run_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT ai_triage_run_metrics_run_agency_key UNIQUE (run_id, agency_id)
);

CREATE TABLE IF NOT EXISTS public.bri_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL,
  profile_id uuid NOT NULL,
  agency_id uuid,
  bri_score numeric(5,2) NOT NULL,
  sofia_engagement_velocity numeric(5,2) DEFAULT 0,
  sentiment_score numeric(5,2) DEFAULT 0,
  cross_property_intent numeric(5,2) DEFAULT 0,
  market_scarcity_factor numeric(5,2) DEFAULT 0,
  reasoning_string text NOT NULL,
  reasoning_factors jsonb DEFAULT '[]'::jsonb,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  tier_at_calculation text DEFAULT 'enterprise'::text,
  CONSTRAINT bri_history_bri_score_check CHECK (((bri_score >= (0)::numeric) AND (bri_score <= (100)::numeric))),
  CONSTRAINT bri_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competition_radar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  district text NOT NULL,
  sector_name text NOT NULL,
  competitor_count integer NOT NULL DEFAULT 0,
  heat_score numeric(4,2) NOT NULL DEFAULT 0,
  trend text NOT NULL DEFAULT 'stable'::text,
  is_demo boolean NOT NULL DEFAULT false,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT competition_radar_heat_score_check CHECK (((heat_score >= (0)::numeric) AND (heat_score <= (1)::numeric))),
  CONSTRAINT competition_radar_trend_check CHECK ((trend = ANY (ARRAY['up'::text, 'down'::text, 'stable'::text]))),
  CONSTRAINT competition_radar_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ghost_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  profile_id uuid,
  city text NOT NULL,
  district text,
  lead_count integer DEFAULT 0,
  last_seen_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ghost_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT ghost_sessions_session_id_key UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS public.ghostwriter_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_address text NOT NULL,
  event_type text NOT NULL,
  letter_html text NOT NULL,
  letter_text text NOT NULL,
  email_sent_to text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ghostwriter_letters_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.integration_settings (
  profile_id uuid NOT NULL,
  calendar_ics_url text,
  imap_host text,
  imap_port integer,
  imap_secure boolean NOT NULL DEFAULT true,
  imap_user text,
  imap_password text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT integration_settings_pkey PRIMARY KEY (profile_id)
);

CREATE TABLE IF NOT EXISTS public.lead_assignment_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  rule_type text NOT NULL,
  profile_ids uuid[] NOT NULL DEFAULT '{}'::uuid[],
  criteria jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_assignment_rules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lead_property_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL,
  property_id text NOT NULL,
  event_type text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_property_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lead_property_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL,
  property_id text NOT NULL,
  score integer NOT NULL DEFAULT 0,
  explanation text NOT NULL DEFAULT ''::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_property_scores_pkey PRIMARY KEY (id),
  CONSTRAINT lead_property_scores_lead_id_property_id_key UNIQUE (lead_id, property_id)
);

CREATE TABLE IF NOT EXISTS public.lead_triage_idempotency (
  lead_id text NOT NULL,
  day_utc date NOT NULL,
  state text NOT NULL,
  processing_started_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_triage_idem_state_ck CHECK ((state = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text]))),
  CONSTRAINT lead_triage_idempotency_pkey PRIMARY KEY (lead_id, day_utc)
);

CREATE TABLE IF NOT EXISTS public.leads_demo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  address text,
  source text DEFAULT 'ai_odhadca'::text,
  estimated_price numeric(12,2),
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  gdpr_consent boolean DEFAULT false,
  gdpr_consent_at timestamp with time zone,
  CONSTRAINT leads_demo_source_check CHECK ((source = ANY (ARRAY['ai_odhadca'::text, 'neighborhood_watch'::text, 'digital_twin'::text]))),
  CONSTRAINT leads_demo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.neighborhood_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  address text NOT NULL,
  area text NOT NULL DEFAULT 'presov'::text,
  event_type text NOT NULL,
  change_amount integer,
  days_ago integer NOT NULL DEFAULT 0,
  is_urgent boolean NOT NULL DEFAULT false,
  source text DEFAULT 'system'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT neighborhood_alerts_event_type_check CHECK ((event_type = ANY (ARRAY['price_drop'::text, 'new_listing'::text, 'sold'::text, 'price_increase'::text]))),
  CONSTRAINT neighborhood_alerts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.neighborhood_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  area text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT neighborhood_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT neighborhood_subscriptions_email_area_key UNIQUE (email, area)
);

CREATE TABLE IF NOT EXISTS public.onboarding_sessions (
  session_id text NOT NULL,
  step integer DEFAULT 1,
  form_data jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_sessions_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.pipeline_moves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL,
  lead_name text NOT NULL DEFAULT ''::text,
  from_status text NOT NULL,
  to_status text NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pipeline_moves_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.priority_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid,
  lead_id text,
  agent_id uuid,
  bri_score numeric(5,2),
  alert_type text NOT NULL,
  message text NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  delivered boolean DEFAULT false,
  deal_summary_pdf_url text,
  CONSTRAINT priority_alerts_alert_type_check CHECK ((alert_type = ANY (ARRAY['sms'::text, 'push'::text, 'email'::text, 'in_app'::text]))),
  CONSTRAINT priority_alerts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.realvia_price_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id text NOT NULL,
  source_id text NOT NULL,
  old_price numeric(12,2),
  new_price numeric(12,2) NOT NULL,
  old_currency text,
  new_currency text NOT NULL DEFAULT 'EUR'::text,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  agency_id uuid,
  CONSTRAINT realvia_price_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.realvia_processing_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  webhook_log_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  retry_count smallint NOT NULL DEFAULT 0,
  max_retries smallint NOT NULL DEFAULT 3,
  next_retry_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  error_message text,
  CONSTRAINT realvia_processing_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text]))),
  CONSTRAINT realvia_processing_queue_pkey PRIMARY KEY (id),
  CONSTRAINT realvia_processing_queue_webhook_log_id_key UNIQUE (webhook_log_id)
);

CREATE TABLE IF NOT EXISTS public.realvia_webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  source_ip text NOT NULL DEFAULT ''::text,
  headers_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload_type text NOT NULL DEFAULT 'advert'::text,
  processed boolean NOT NULL DEFAULT false,
  processing_error text,
  agency_id uuid,
  CONSTRAINT realvia_webhook_logs_payload_type_check CHECK ((payload_type = ANY (ARRAY['advert'::text, 'delete'::text, 'unknown'::text]))),
  CONSTRAINT realvia_webhook_logs_pkey PRIMARY KEY (id),
  CONSTRAINT realvia_webhook_logs_request_id_key UNIQUE (request_id)
);

CREATE TABLE IF NOT EXISTS public.revolis_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  email text,
  data jsonb NOT NULL,
  bri_index integer GENERATED ALWAYS AS ((((data -> 'ai_metrics'::text) ->> 'buyer_readiness_index'::text))::integer) STORED,
  CONSTRAINT revolis_leads_pkey PRIMARY KEY (id),
  CONSTRAINT revolis_leads_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.revolis_zaujemcovia (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text,
  profil jsonb,
  readiness_score integer DEFAULT 0,
  behavioral_notes text,
  last_activity timestamp with time zone DEFAULT now(),
  source_portal text,
  raw_data jsonb,
  external_id text,
  preferred_location text,
  CONSTRAINT revolis_zaujemcovia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roi_guarantee_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid,
  email text NOT NULL,
  agency_name text,
  plan text NOT NULL,
  claim_reason text,
  status text DEFAULT 'pending'::text,
  refund_amount numeric(10,2),
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT roi_guarantee_claims_plan_check CHECK ((plan = ANY (ARRAY['starter'::text, 'pro'::text, 'enterprise'::text]))),
  CONSTRAINT roi_guarantee_claims_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'paid'::text]))),
  CONSTRAINT roi_guarantee_claims_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.saas_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL DEFAULT ''::text,
  company text NOT NULL,
  agents_count integer NOT NULL DEFAULT 1,
  city text NOT NULL DEFAULT ''::text,
  note text NOT NULL DEFAULT ''::text,
  source text NOT NULL DEFAULT 'Demo request'::text,
  status text NOT NULL DEFAULT 'new'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT saas_leads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shadow_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  lead_id text,
  property_id text,
  signal_type text NOT NULL,
  confidence_score numeric(5,2),
  life_stage_trigger text,
  ai_reasoning text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  property_listed boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  alerted_at timestamp with time zone,
  acted_at timestamp with time zone,
  CONSTRAINT shadow_inventory_confidence_score_check CHECK (((confidence_score >= (0)::numeric) AND (confidence_score <= (100)::numeric))),
  CONSTRAINT shadow_inventory_signal_type_check CHECK ((signal_type = ANY (ARRAY['dormant_revival'::text, 'predictive_relisting'::text, 'hidden_match'::text, 'life_stage_trigger'::text]))),
  CONSTRAINT shadow_inventory_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'alerted'::text, 'acted'::text, 'dismissed'::text]))),
  CONSTRAINT shadow_inventory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team_licenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  license_type text NOT NULL,
  owner_profile_id uuid,
  active_force_slots integer NOT NULL DEFAULT 1,
  used_slots integer DEFAULT 0,
  stripe_subscription_id text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_licenses_license_type_check CHECK ((license_type = ANY (ARRAY['market_vision'::text, 'protocol_authority'::text]))),
  CONSTRAINT team_licenses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usage_metrics_daily (
  agency_id uuid NOT NULL,
  metric_day date NOT NULL,
  metric text NOT NULL,
  amount bigint NOT NULL DEFAULT 0,
  CONSTRAINT usage_metrics_daily_pkey PRIMARY KEY (agency_id, metric_day, metric)
);

-- -------------------------------------------------------------------------
-- 3. Foreign keys.
--    Applied after every table above exists, so declaration order is irrelevant.
--    Each is guarded on pg_constraint: ALTER TABLE ... ADD CONSTRAINT has no
--    IF NOT EXISTS form, and re-running must not error on production.
-- -------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ai_triage_feedback_agency_id_fkey' AND conrelid = 'public.ai_triage_feedback'::regclass
  ) THEN
    ALTER TABLE public.ai_triage_feedback ADD CONSTRAINT ai_triage_feedback_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ai_triage_feedback_lead_id_fkey' AND conrelid = 'public.ai_triage_feedback'::regclass
  ) THEN
    ALTER TABLE public.ai_triage_feedback ADD CONSTRAINT ai_triage_feedback_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ai_triage_feedback_profile_id_fkey' AND conrelid = 'public.ai_triage_feedback'::regclass
  ) THEN
    ALTER TABLE public.ai_triage_feedback ADD CONSTRAINT ai_triage_feedback_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ai_triage_run_metrics_agency_id_fkey' AND conrelid = 'public.ai_triage_run_metrics'::regclass
  ) THEN
    ALTER TABLE public.ai_triage_run_metrics ADD CONSTRAINT ai_triage_run_metrics_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'bri_history_agency_id_fkey' AND conrelid = 'public.bri_history'::regclass
  ) THEN
    ALTER TABLE public.bri_history ADD CONSTRAINT bri_history_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'bri_history_lead_id_fkey' AND conrelid = 'public.bri_history'::regclass
  ) THEN
    ALTER TABLE public.bri_history ADD CONSTRAINT bri_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'bri_history_profile_id_fkey' AND conrelid = 'public.bri_history'::regclass
  ) THEN
    ALTER TABLE public.bri_history ADD CONSTRAINT bri_history_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ghost_sessions_profile_id_fkey' AND conrelid = 'public.ghost_sessions'::regclass
  ) THEN
    ALTER TABLE public.ghost_sessions ADD CONSTRAINT ghost_sessions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'integration_settings_profile_id_fkey' AND conrelid = 'public.integration_settings'::regclass
  ) THEN
    ALTER TABLE public.integration_settings ADD CONSTRAINT integration_settings_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'lead_property_events_lead_id_fkey' AND conrelid = 'public.lead_property_events'::regclass
  ) THEN
    ALTER TABLE public.lead_property_events ADD CONSTRAINT lead_property_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'lead_property_events_property_id_fkey' AND conrelid = 'public.lead_property_events'::regclass
  ) THEN
    ALTER TABLE public.lead_property_events ADD CONSTRAINT lead_property_events_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'lead_property_scores_lead_id_fkey' AND conrelid = 'public.lead_property_scores'::regclass
  ) THEN
    ALTER TABLE public.lead_property_scores ADD CONSTRAINT lead_property_scores_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'lead_property_scores_property_id_fkey' AND conrelid = 'public.lead_property_scores'::regclass
  ) THEN
    ALTER TABLE public.lead_property_scores ADD CONSTRAINT lead_property_scores_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'lead_triage_idempotency_lead_id_fkey' AND conrelid = 'public.lead_triage_idempotency'::regclass
  ) THEN
    ALTER TABLE public.lead_triage_idempotency ADD CONSTRAINT lead_triage_idempotency_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pipeline_moves_lead_id_fkey' AND conrelid = 'public.pipeline_moves'::regclass
  ) THEN
    ALTER TABLE public.pipeline_moves ADD CONSTRAINT pipeline_moves_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'priority_alerts_agency_id_fkey' AND conrelid = 'public.priority_alerts'::regclass
  ) THEN
    ALTER TABLE public.priority_alerts ADD CONSTRAINT priority_alerts_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'priority_alerts_agent_id_fkey' AND conrelid = 'public.priority_alerts'::regclass
  ) THEN
    ALTER TABLE public.priority_alerts ADD CONSTRAINT priority_alerts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES profiles(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'priority_alerts_lead_id_fkey' AND conrelid = 'public.priority_alerts'::regclass
  ) THEN
    ALTER TABLE public.priority_alerts ADD CONSTRAINT priority_alerts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'realvia_price_history_agency_id_fkey' AND conrelid = 'public.realvia_price_history'::regclass
  ) THEN
    ALTER TABLE public.realvia_price_history ADD CONSTRAINT realvia_price_history_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'realvia_processing_queue_webhook_log_id_fkey' AND conrelid = 'public.realvia_processing_queue'::regclass
  ) THEN
    ALTER TABLE public.realvia_processing_queue ADD CONSTRAINT realvia_processing_queue_webhook_log_id_fkey FOREIGN KEY (webhook_log_id) REFERENCES realvia_webhook_logs(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'realvia_webhook_logs_agency_id_fkey' AND conrelid = 'public.realvia_webhook_logs'::regclass
  ) THEN
    ALTER TABLE public.realvia_webhook_logs ADD CONSTRAINT realvia_webhook_logs_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'roi_guarantee_claims_profile_id_fkey' AND conrelid = 'public.roi_guarantee_claims'::regclass
  ) THEN
    ALTER TABLE public.roi_guarantee_claims ADD CONSTRAINT roi_guarantee_claims_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'shadow_inventory_agency_id_fkey' AND conrelid = 'public.shadow_inventory'::regclass
  ) THEN
    ALTER TABLE public.shadow_inventory ADD CONSTRAINT shadow_inventory_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'shadow_inventory_lead_id_fkey' AND conrelid = 'public.shadow_inventory'::regclass
  ) THEN
    ALTER TABLE public.shadow_inventory ADD CONSTRAINT shadow_inventory_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'shadow_inventory_property_id_fkey' AND conrelid = 'public.shadow_inventory'::regclass
  ) THEN
    ALTER TABLE public.shadow_inventory ADD CONSTRAINT shadow_inventory_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'team_licenses_owner_profile_id_fkey' AND conrelid = 'public.team_licenses'::regclass
  ) THEN
    ALTER TABLE public.team_licenses ADD CONSTRAINT team_licenses_owner_profile_id_fkey FOREIGN KEY (owner_profile_id) REFERENCES profiles(id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'usage_metrics_daily_agency_id_fkey' AND conrelid = 'public.usage_metrics_daily'::regclass
  ) THEN
    ALTER TABLE public.usage_metrics_daily ADD CONSTRAINT usage_metrics_daily_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
  END IF;
END $$;

-- -------------------------------------------------------------------------
-- 4. Indexes that do not back a constraint.
--    Reproduced as production has them, including the duplicates production
--    actually carries (idx_bri_lead / idx_bri_history_lead and
--    idx_shadow_agency / idx_shadow_inventory_agency are the same index twice).
--    A baseline records what is there; de-duplicating them is a separate call.
-- -------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS ai_triage_feedback_agency_created_idx ON public.ai_triage_feedback USING btree (agency_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ai_triage_feedback_lead_idx ON public.ai_triage_feedback USING btree (lead_id);
CREATE INDEX IF NOT EXISTS ai_triage_run_metrics_agency_finished_idx ON public.ai_triage_run_metrics USING btree (agency_id, finished_at DESC);
CREATE INDEX IF NOT EXISTS ai_triage_run_metrics_run_id_idx ON public.ai_triage_run_metrics USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_bri_history_agency ON public.bri_history USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_bri_history_lead ON public.bri_history USING btree (lead_id);
CREATE INDEX IF NOT EXISTS idx_bri_history_score ON public.bri_history USING btree (bri_score DESC);
CREATE INDEX IF NOT EXISTS idx_bri_lead ON public.bri_history USING btree (lead_id);
CREATE INDEX IF NOT EXISTS idx_bri_score ON public.bri_history USING btree (bri_score DESC);
CREATE INDEX IF NOT EXISTS idx_competition_radar_district ON public.competition_radar USING btree (district);
CREATE INDEX IF NOT EXISTS idx_ghost_session ON public.ghost_sessions USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_ghost_sessions_profile ON public.ghost_sessions USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_ghost_sessions_session_id ON public.ghost_sessions USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_integration_settings_updated_at ON public.integration_settings USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_assignment_rules_active ON public.lead_assignment_rules USING btree (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS lead_property_events_event_type_idx ON public.lead_property_events USING btree (event_type);
CREATE INDEX IF NOT EXISTS lead_property_events_lead_id_idx ON public.lead_property_events USING btree (lead_id);
CREATE INDEX IF NOT EXISTS lead_property_events_property_id_idx ON public.lead_property_events USING btree (property_id);
CREATE INDEX IF NOT EXISTS lead_property_scores_lead_id_idx ON public.lead_property_scores USING btree (lead_id);
CREATE INDEX IF NOT EXISTS lead_property_scores_property_id_idx ON public.lead_property_scores USING btree (property_id);
CREATE INDEX IF NOT EXISTS lead_property_scores_score_idx ON public.lead_property_scores USING btree (score);
CREATE INDEX IF NOT EXISTS lead_triage_idem_day_state_idx ON public.lead_triage_idempotency USING btree (day_utc, state);
CREATE INDEX IF NOT EXISTS idx_leads_demo_created ON public.leads_demo USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_demo_email ON public.leads_demo USING btree (email);
CREATE INDEX IF NOT EXISTS idx_priority_alerts_agency ON public.priority_alerts USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_priority_alerts_sent_at ON public.priority_alerts USING btree (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_rph_property ON public.realvia_price_history USING btree (property_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_rph_source ON public.realvia_price_history USING btree (source_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_rpq_created ON public.realvia_processing_queue USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rpq_pending ON public.realvia_processing_queue USING btree (status, next_retry_at) WHERE (status = ANY (ARRAY['pending'::text, 'failed'::text]));
CREATE INDEX IF NOT EXISTS idx_rwl_agency ON public.realvia_webhook_logs USING btree (agency_id) WHERE (agency_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rwl_processed ON public.realvia_webhook_logs USING btree (processed) WHERE (processed = false);
CREATE INDEX IF NOT EXISTS idx_rwl_received_at ON public.realvia_webhook_logs USING btree (received_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_data_gin ON public.revolis_leads USING gin (data);
CREATE INDEX IF NOT EXISTS idx_external_id ON public.revolis_zaujemcovia USING btree (external_id);
CREATE INDEX IF NOT EXISTS idx_readiness_score ON public.revolis_zaujemcovia USING btree (readiness_score DESC);
CREATE INDEX IF NOT EXISTS idx_roi_claims_email ON public.roi_guarantee_claims USING btree (email);
CREATE INDEX IF NOT EXISTS idx_shadow_agency ON public.shadow_inventory USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_shadow_inventory_agency ON public.shadow_inventory USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_shadow_inventory_signal ON public.shadow_inventory USING btree (signal_type);
CREATE INDEX IF NOT EXISTS idx_shadow_signal ON public.shadow_inventory USING btree (signal_type);
CREATE INDEX IF NOT EXISTS idx_team_licenses_agency ON public.team_licenses USING btree (agency_id);

-- -------------------------------------------------------------------------
-- 5. Row level security.
--    Every one of the 30 has RLS enabled in production. Without this section a
--    clean database would get the tables WITHOUT RLS -- a security regression
--    against production introduced by the very file meant to reproduce it.
-- -------------------------------------------------------------------------

ALTER TABLE public."AI AGENT AUTOMAT ONBOARDING" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AI AGENT AUTOMAT ONBOARDING no.2.01" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_triage_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_triage_run_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bri_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_radar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ghost_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ghostwriter_letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."gpmmfashion@gmail.com tabulka" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integration_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_assignment_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_property_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_property_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_triage_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads_demo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.neighborhood_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.neighborhood_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_moves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.priority_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.realvia_price_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.realvia_processing_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.realvia_webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revolis_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revolis_zaujemcovia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roi_guarantee_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saas_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shadow_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_metrics_daily ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 6. Policies, exactly as production has them.
--
--    Read the `onboarding_sessions` policy below before assuming this section
--    is routine. It is `TO anon USING (true) WITH CHECK (true)` -- a full
--    anonymous read AND write hole, the same shape #697 and #702 were opened to
--    close on other tables. Neither of those covered this one.
--
--    It is reproduced here unchanged and on purpose: this file's job is to make
--    a clean database match production, not to change production behaviour
--    behind a baseline commit. Closing it is a separate, deliberate change with
--    its own gate -- flagged, not fixed, and not silently carried.
--
--    Each policy is dropped first: CREATE POLICY has no IF NOT EXISTS form.
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS ai_triage_feedback_insert_own_agency ON public.ai_triage_feedback;
CREATE POLICY ai_triage_feedback_insert_own_agency ON public.ai_triage_feedback AS PERMISSIVE FOR INSERT TO public WITH CHECK (((profile_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM leads l
  WHERE ((l.id = ai_triage_feedback.lead_id) AND (l.agency_id IS NOT NULL) AND (l.agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)))))));

DROP POLICY IF EXISTS ai_triage_feedback_select_author_or_leadership ON public.ai_triage_feedback;
CREATE POLICY ai_triage_feedback_select_author_or_leadership ON public.ai_triage_feedback AS PERMISSIVE FOR SELECT TO public USING (((agency_id IS NOT NULL) AND (agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)) AND ((profile_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.agency_id = ai_triage_feedback.agency_id) AND (lower(TRIM(BOTH FROM p.role)) = ANY (ARRAY['owner'::text, 'manager'::text]))))))));

DROP POLICY IF EXISTS ai_triage_run_metrics_agency_select ON public.ai_triage_run_metrics;
CREATE POLICY ai_triage_run_metrics_agency_select ON public.ai_triage_run_metrics AS PERMISSIVE FOR SELECT TO public USING ((agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)));

DROP POLICY IF EXISTS "Enterprise BRI access" ON public.bri_history;
CREATE POLICY "Enterprise BRI access" ON public.bri_history AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.auth_user_id = auth.uid()) AND (profiles.account_tier = 'enterprise'::text)))));

DROP POLICY IF EXISTS "Locked BRI read-only" ON public.bri_history;
CREATE POLICY "Locked BRI read-only" ON public.bri_history AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.auth_user_id = auth.uid()) AND (profiles.tier_locked_at IS NOT NULL)))));

DROP POLICY IF EXISTS bri_history_tenant ON public.bri_history;
CREATE POLICY bri_history_tenant ON public.bri_history AS PERMISSIVE FOR ALL TO authenticated USING (((agency_id IS NULL) OR (agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)))) WITH CHECK (((agency_id IS NULL) OR (agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth))));

DROP POLICY IF EXISTS "authenticated read radar" ON public.competition_radar;
CREATE POLICY "authenticated read radar" ON public.competition_radar AS PERMISSIVE FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "service role competition_radar" ON public.competition_radar;
CREATE POLICY "service role competition_radar" ON public.competition_radar AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Users see own ghost sessions" ON public.ghost_sessions;
CREATE POLICY "Users see own ghost sessions" ON public.ghost_sessions AS PERMISSIVE FOR ALL TO public USING ((profile_id IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS "service role ghost_sessions" ON public.ghost_sessions;
CREATE POLICY "service role ghost_sessions" ON public.ghost_sessions AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user own ghost session" ON public.ghost_sessions;
CREATE POLICY "user own ghost session" ON public.ghost_sessions AS PERMISSIVE FOR SELECT TO public USING ((profile_id = auth.uid()));

DROP POLICY IF EXISTS service_only ON public.leads_demo;
CREATE POLICY service_only ON public.leads_demo AS PERMISSIVE FOR SELECT TO public USING (false);

-- See the section header: this is an open anonymous read/write hole, carried
-- over unchanged so the baseline matches production. Closing it is its own task.
DROP POLICY IF EXISTS "Allow anon access" ON public.onboarding_sessions;
CREATE POLICY "Allow anon access" ON public.onboarding_sessions AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS pipeline_moves_tenant_select ON public.pipeline_moves;
CREATE POLICY pipeline_moves_tenant_select ON public.pipeline_moves AS PERMISSIVE FOR SELECT TO authenticated USING ((lead_id IN ( SELECT leads.id
   FROM leads
  WHERE ((leads.agency_id IS NULL) OR (leads.agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth))))));

DROP POLICY IF EXISTS pipeline_moves_tenant_write ON public.pipeline_moves;
CREATE POLICY pipeline_moves_tenant_write ON public.pipeline_moves AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((lead_id IN ( SELECT leads.id
   FROM leads
  WHERE ((leads.agency_id IS NULL) OR (leads.agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth))))));

DROP POLICY IF EXISTS priority_alerts_tenant ON public.priority_alerts;
CREATE POLICY priority_alerts_tenant ON public.priority_alerts AS PERMISSIVE FOR ALL TO authenticated USING (((agency_id IS NULL) OR (agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)))) WITH CHECK (((agency_id IS NULL) OR (agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth))));

DROP POLICY IF EXISTS realvia_price_history_agency_read ON public.realvia_price_history;
CREATE POLICY realvia_price_history_agency_read ON public.realvia_price_history AS PERMISSIVE FOR SELECT TO authenticated USING ((agency_id IN ( SELECT profiles.agency_id
   FROM profiles
  WHERE (profiles.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS realvia_price_history_service_role ON public.realvia_price_history;
CREATE POLICY realvia_price_history_service_role ON public.realvia_price_history AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));

DROP POLICY IF EXISTS realvia_processing_queue_service_role ON public.realvia_processing_queue;
CREATE POLICY realvia_processing_queue_service_role ON public.realvia_processing_queue AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));

DROP POLICY IF EXISTS realvia_webhook_logs_service_role ON public.realvia_webhook_logs;
CREATE POLICY realvia_webhook_logs_service_role ON public.realvia_webhook_logs AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));

DROP POLICY IF EXISTS "Users insert own claims" ON public.roi_guarantee_claims;
CREATE POLICY "Users insert own claims" ON public.roi_guarantee_claims AS PERMISSIVE FOR INSERT TO public WITH CHECK ((profile_id IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS "Users see own claims" ON public.roi_guarantee_claims;
CREATE POLICY "Users see own claims" ON public.roi_guarantee_claims AS PERMISSIVE FOR SELECT TO public USING ((profile_id IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS saas_leads_platform_admin ON public.saas_leads;
CREATE POLICY saas_leads_platform_admin ON public.saas_leads AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.auth_user_id = auth.uid()) AND p.is_platform_admin)))) WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.auth_user_id = auth.uid()) AND p.is_platform_admin))));

DROP POLICY IF EXISTS "Enterprise Shadow Inventory" ON public.shadow_inventory;
CREATE POLICY "Enterprise Shadow Inventory" ON public.shadow_inventory AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.auth_user_id = auth.uid()) AND (profiles.account_tier = 'enterprise'::text)))));

DROP POLICY IF EXISTS shadow_inventory_tenant ON public.shadow_inventory;
CREATE POLICY shadow_inventory_tenant ON public.shadow_inventory AS PERMISSIVE FOR ALL TO authenticated USING ((agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth))) WITH CHECK ((agency_id IN ( SELECT profile_agencies_for_auth() AS profile_agencies_for_auth)));

DROP POLICY IF EXISTS "Agency members see own license" ON public.team_licenses;
CREATE POLICY "Agency members see own license" ON public.team_licenses AS PERMISSIVE FOR SELECT TO public USING ((agency_id IN ( SELECT profiles.agency_id
   FROM profiles
  WHERE (profiles.auth_user_id = auth.uid()))));

DROP POLICY IF EXISTS "agency owner manage license" ON public.team_licenses;
CREATE POLICY "agency owner manage license" ON public.team_licenses AS PERMISSIVE FOR ALL TO public USING ((agency_id = auth.uid()));

DROP POLICY IF EXISTS "service role team_licenses" ON public.team_licenses;
CREATE POLICY "service role team_licenses" ON public.team_licenses AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS usage_metrics_select_tenant ON public.usage_metrics_daily;
CREATE POLICY usage_metrics_select_tenant ON public.usage_metrics_daily AS PERMISSIVE FOR SELECT TO authenticated USING ((agency_id IN ( SELECT p.agency_id
   FROM profiles p
  WHERE ((p.auth_user_id = auth.uid()) AND (p.agency_id IS NOT NULL)))));

-- ---------------------------------------------------------------------------
-- 7. Triggers.
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tr_ai_triage_feedback_set_agency ON public.ai_triage_feedback;
CREATE TRIGGER tr_ai_triage_feedback_set_agency BEFORE INSERT ON public.ai_triage_feedback FOR EACH ROW EXECUTE FUNCTION ai_triage_feedback_set_agency();

DROP TRIGGER IF EXISTS team_licenses_updated_at ON public.team_licenses;
CREATE TRIGGER team_licenses_updated_at BEFORE UPDATE ON public.team_licenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();
