-- Lead dossier storage separated from ai_engine payload.
-- Keeps research-agent output isolated from triage AI columns.

ALTER TABLE IF EXISTS public.leads
  ADD COLUMN IF NOT EXISTS dossier JSONB;

COMMENT ON COLUMN public.leads.dossier IS
  'Structured research dossier JSON generated by research-agent buildDossier().';
