// ================================================================
// Revolis.AI — Event System Types
// Generated by create_event_pipeline.sh
// ================================================================

// EVENTS-WIRE-01 — slovníky sú RUNTIME polia a typy sa z nich derivujú, nie
// naopak. Dôvod: `public.events` má CHECK len na `entity_type`; `event_type` je
// na úrovni DB voľný text, takže preklep v názve sa zapíše a navždy otrávi
// pipeline (BRI počíta nad `event_type`, ktorý nikto nikdy nevyhodnotí). Jediná
// brána je teda kód — a brána, ktorá existuje len ako TypeScript typ, na
// hranici HTTP neplatí nič. Odtiaľ tieto polia: `/api/events` nad nimi validuje
// za behu a pridanie nového typu na jednom mieste drží typ aj validátor v zhode.
export const ENTITY_TYPES = [
  'lead', 'property', 'contact', 'message',
  'call', 'import', 'export', 'session', 'system',
] as const

/** All allowed event types — exhaustive list, runtime + typ v jednom zdroji. */
export const EVENT_TYPES = [
  // Lead lifecycle
  'lead_created', 'lead_viewed', 'lead_updated', 'lead_qualified',
  'lead_disqualified', 'lead_archived', 'lead_reactivated',
  // Messaging
  // `message_initiated` = človek stlačil Email (otvoril sa mailto), nie že sa
  // e-mail odoslal. Odoslanie tvrdí `message_sent`. Rozdiel je zámerný:
  // `/api/leads/[id]/contact-attempt` o doručení nič nevie a nesmie to tvrdiť.
  'message_initiated',
  'message_sent', 'message_opened', 'message_clicked', 'message_replied', 'message_failed',
  // Calls
  'call_initiated', 'call_completed', 'call_missed', 'call_analyzed',
  // Property
  'property_viewed', 'property_saved', 'property_matched',
  'property_price_changed', 'property_imported', 'lv_change_detected',
  // Portal & imports
  'import_started', 'import_completed', 'import_failed',
  'arbitrage_detected', 'price_trail_updated',
  // User actions (tracked for Integrity Monitor)
  'export_contacts', 'bulk_view', 'csv_download', 'data_export',
  // Session
  'session_started', 'session_ended', 'page_viewed',
  // AI
  'bri_score_computed', 'morning_brief_sent', 'ghost_resurrection_triggered',
  'ai_suggestion_shown', 'ai_suggestion_accepted', 'ai_suggestion_dismissed',
  // System
  'system_alert', 'integrity_alert', 'lv_monitor_run',
] as const

export type EntityType = (typeof ENTITY_TYPES)[number]
export type EventType  = (typeof EVENT_TYPES)[number]

export interface RevolisEvent {
  id:           string
  profile_id:   string
  entity_type:  EntityType
  entity_id:    string | null
  event_type:   EventType
  payload:      Record<string, unknown>
  session_id:   string | null
  created_at:   string
}

export interface BRIScore {
  lead_id:          string
  bri_score:        number   // 0–100
  recency_score:    number
  engagement_score: number
  source_score:     number
  match_score:      number
  time_decay:       number
  score_factors:    Record<string, number>
  computed_at:      string
}

export interface BRIScoreChange {
  lead_id:    string
  old_score:  number
  new_score:  number
  delta:      number
  trigger:    EventType
  timestamp:  string
}

export interface IntegrityAlert {
  id:            string
  profile_id:    string
  triggered_by:  string
  alert_type:    'bulk_export' | 'unusual_access' | 'off_hours' | 'mass_view' | 'data_download'
  threshold_hit: number
  payload:       Record<string, unknown>
  resolved_at:   string | null
  created_at:    string
}

export interface MorningBrief {
  profile_id:         string
  generated_at:       string
  top_lead:           { id: string; name: string; score: number; reason: string }
  overnight_changes:  Array<{ type: string; description: string; entity_id: string }>
  recommended_action: { action: string; lead_id: string; context: string }
  stats: {
    active_leads:    number
    new_inquiries:   number
    score_increases: number
    lv_changes:      number
  }
}
