// ================================================================
// Revolis.AI — Event System Types
// Generated by create_event_pipeline.sh
// ================================================================

export type EntityType =
  | 'lead' | 'property' | 'contact' | 'message'
  | 'call' | 'import' | 'export' | 'session' | 'system'

// All allowed event types — exhaustive list for type safety
export type EventType =
  // Lead lifecycle
  | 'lead_created' | 'lead_viewed' | 'lead_updated' | 'lead_qualified'
  | 'lead_disqualified' | 'lead_archived' | 'lead_reactivated'
  // Messaging
  | 'message_sent' | 'message_opened' | 'message_replied' | 'message_failed'
  // Calls
  | 'call_initiated' | 'call_completed' | 'call_missed' | 'call_analyzed'
  // Property
  | 'property_viewed' | 'property_saved' | 'property_matched'
  | 'property_price_changed' | 'property_imported' | 'lv_change_detected'
  // Portal & imports
  | 'import_started' | 'import_completed' | 'import_failed'
  | 'arbitrage_detected' | 'price_trail_updated'
  // User actions (tracked for Integrity Monitor)
  | 'export_contacts' | 'bulk_view' | 'csv_download' | 'data_export'
  // Session
  | 'session_started' | 'session_ended' | 'page_viewed'
  // AI
  | 'bri_score_computed' | 'morning_brief_sent' | 'ghost_resurrection_triggered'
  | 'ai_suggestion_shown' | 'ai_suggestion_accepted' | 'ai_suggestion_dismissed'
  // System
  | 'system_alert' | 'integrity_alert' | 'lv_monitor_run'

export interface RevolisEvent {
  id:           string
  profile_id:   string
  entity_type:  EntityType
  entity_id:    string | null
  event_type:   EventType
  payload:      Record<string, unknown>
  session_id:   string | null
  created_at:   string
}

export interface BRIScore {
  lead_id:          string
  bri_score:        number   // 0–100
  recency_score:    number
  engagement_score: number
  source_score:     number
  match_score:      number
  time_decay:       number
  score_factors:    Record<string, number>
  computed_at:      string
}

export interface BRIScoreChange {
  lead_id:    string
  old_score:  number
  new_score:  number
  delta:      number
  trigger:    EventType
  timestamp:  string
}

export interface IntegrityAlert {
  id:            string
  profile_id:    string
  triggered_by:  string
  alert_type:    'bulk_export' | 'unusual_access' | 'off_hours' | 'mass_view' | 'data_download'
  threshold_hit: number
  payload:       Record<string, unknown>
  resolved_at:   string | null
  created_at:    string
}

export interface MorningBrief {
  profile_id:         string
  generated_at:       string
  top_lead:           { id: string; name: string; score: number; reason: string }
  overnight_changes:  Array<{ type: string; description: string; entity_id: string }>
  recommended_action: { action: string; lead_id: string; context: string }
  stats: {
    active_leads:    number
    new_inquiries:   number
    score_increases: number
    lv_changes:      number
  }
}
