import type { PlaybookItemDto } from "./types";

export const mockBusyDay: PlaybookItemDto[] = [
  {
    id: "call-jan",
    leadId: "mock-jan",
    type: "CALL",
    buyerName: "Ján Novák",
    buyerScore: 92,
    title: "Zavolaj Jánovi (92/100)",
    subtitle: "5× si pozrel byt na Šancovej, požiadal o obhliadku",
    reason: "Silný záujem + vysoká aktivita posledné 2 dni",
    badges: ["HOT NOW", "BRI 92"],
    ctaLabel: "Zavolať",
    priority: 92,
  },
  {
    id: "call-petra",
    leadId: "mock-petra",
    type: "CALL",
    buyerName: "Petra Kováčová",
    buyerScore: 88,
    title: "Zavolaj Petre (88/100)",
    subtitle: "Klikla na ponuku 3-izbového bytu v Ružinove",
    reason: "3× klik z kampane + uložená ponuka",
    badges: ["HIGH PRIORITY"],
    ctaLabel: "Zavolať",
    priority: 88,
  },
  {
    id: "viewing-marek",
    leadId: "mock-marek",
    type: "OPPORTUNITY",
    buyerName: "Marek Šimko",
    buyerScore: 84,
    title: "Dohodni obhliadku s Marekom (84/100)",
    subtitle: "Hľadá 4-izbový byt, nový listing sedí na 98 %",
    reason: "Perfektný fit + rastúca aktivita",
    badges: ["MATCH"],
    ctaLabel: "Navrhnúť termín",
    priority: 84,
  },
  {
    id: "contract-anna",
    leadId: "mock-anna",
    type: "OPPORTUNITY",
    buyerName: "Anna Hrivnáková",
    buyerScore: 79,
    title: "Priprav podpis kúpnej zmluvy",
    subtitle: "Kupujúca potvrdila záujem o dom v Lamači",
    reason: "Záverečná fáza procesu",
    badges: ["CLOSING"],
    ctaLabel: "Pripraviť dokumenty",
    priority: 79,
  },
  {
    id: "risk-racianska",
    leadId: "mock-racianska",
    type: "RISK",
    title: "Byt na Račianskej stagnuje",
    subtitle: "Pokles záujmu o 52 % za 14 dní",
    reason: "Žiadne nové dopyty, menej zobrazení",
    badges: ["RIZIKO"],
    ctaLabel: "Navrhnúť úpravu ceny",
    priority: 60,
  },
  {
    id: "followup-milan",
    leadId: "mock-milan",
    type: "MESSAGE",
    buyerName: "Milan Krajčír",
    buyerScore: 73,
    title: "Pošli follow-up Milanovi (73/100)",
    subtitle: "Neodpovedal na poslednú ponuku",
    reason: "Stále vysoký záujem, ale bez reakcie",
    badges: ["FOLLOW-UP"],
    ctaLabel: "Poslať správu",
    priority: 73,
  },
  {
    id: "viewing-today-1",
    leadId: "mock-lucia",
    type: "CALL",
    buyerName: "Lucia Šoltésová",
    buyerScore: 81,
    title: "Potvrď dnešnú obhliadku s Luciou",
    subtitle: "Obhliadka o 16:00 – 3-izbový byt, Staré Mesto",
    reason: "Vysoký záujem + potvrdený termín",
    badges: ["TODAY"],
    ctaLabel: "Potvrdiť",
    priority: 81,
  },
  {
    id: "viewing-today-2",
    leadId: "mock-tomas",
    type: "CALL",
    buyerName: "Tomáš Bielik",
    buyerScore: 77,
    title: "Pripomeň Tomášovi obhliadku",
    subtitle: "Obhliadka o 18:00 – novostavba Slnečnice",
    reason: "Dôležitý klient + vysoký fit",
    badges: ["REMINDER"],
    ctaLabel: "Zavolať",
    priority: 77,
  },
  {
    id: "crossmatch-1",
    leadId: "mock-zuzana",
    type: "OPPORTUNITY",
    buyerName: "Zuzana Šimková",
    buyerScore: 82,
    title: "Pošli Zuzane nový matching byt",
    subtitle: "Nový listing sedí na 94 % preferencií",
    reason: "Silný fit + vysoký BRI",
    badges: ["MATCH"],
    ctaLabel: "Poslať ponuku",
    priority: 82,
  },
  {
    id: "crossmatch-2",
    leadId: "mock-roman",
    type: "OPPORTUNITY",
    buyerName: "Roman Kubiš",
    buyerScore: 75,
    title: "Odporuč Romanovi alternatívny byt",
    subtitle: "Pôvodný byt rezervovaný, máme 2 podobné",
    reason: "Zachrániš obchod",
    badges: ["ALTERNATÍVA"],
    ctaLabel: "Poslať alternatívu",
    priority: 75,
  },
];
