import { describe, expect, it } from 'vitest'
import { mapMatchToAcquisitionCandidate } from '../map-to-acquisition'
import type { ArbitrageMatch } from '@/types/arbitrage'

function baseMatch(overrides: Partial<ArbitrageMatch> = {}): ArbitrageMatch {
  return {
    id: 'match-1',
    profile_id: 'profile-1',
    listing_portal: 'p1',
    listing_bazos: 'b1',
    price_portal: 200000,
    price_bazos: 160000,
    delta_eur: 40000,
    delta_pct: 20,
    match_score: 0.9,
    match_reasons: ['same_street'],
    city: 'Košice',
    address_display: 'Hlavná 1, Košice',
    price_drop_count: 0,
    days_on_market: 5,
    seller_is_private: true,
    status: 'new',
    dismissed_reason: null,
    lead_id: null,
    detected_at: '2026-01-01T00:00:00Z',
    expires_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    portal_listing: {
      id: 'p1',
      profile_id: null,
      source: 'nehnutelnosti_sk',
      external_id: 'e1',
      external_url: null,
      title: '3-izb byt',
      price: 200000,
      currency: 'EUR',
      price_per_m2: null,
      area_m2: 72,
      rooms: 3,
      floor: null,
      property_type: 'apartment',
      transaction_type: 'sale',
      street: 'Hlavná',
      city: 'Košice',
      district: null,
      region: null,
      postal_code: null,
      lat: null,
      lng: null,
      location_raw: null,
      location_hash: null,
      property_hash: null,
      seller_type: 'agency',
      seller_name: 'Agent X',
      seller_phone: null,
      description: null,
      cover_photo_url: null,
      first_seen_at: '2026-01-01',
      last_seen_at: '2026-01-01',
      last_price: null,
      is_active: true,
    },
    bazos_listing: {
      id: 'b1',
      profile_id: null,
      source: 'bazos_sk',
      external_id: 'e2',
      external_url: 'https://bazos.sk/x',
      title: 'Byt Bazoš',
      price: 160000,
      currency: 'EUR',
      price_per_m2: null,
      area_m2: 72,
      rooms: 3,
      floor: null,
      property_type: 'apartment',
      transaction_type: 'sale',
      street: null,
      city: 'Košice',
      district: null,
      region: null,
      postal_code: null,
      lat: null,
      lng: null,
      location_raw: null,
      location_hash: null,
      property_hash: null,
      seller_type: 'private',
      seller_name: 'Private Seller',
      seller_phone: '+421911111111',
      description: null,
      cover_photo_url: null,
      first_seen_at: '2026-01-01',
      last_seen_at: '2026-01-01',
      last_price: null,
      is_active: true,
    },
    ...overrides,
  }
}

describe('mapMatchToAcquisitionCandidate', () => {
  it('uses match id and maps score from match_score', () => {
    const c = mapMatchToAcquisitionCandidate(baseMatch())
    expect(c.id).toBe('match-1')
    expect(c.arbitrageScore).toBe(90)
    expect(c.interestedAddress).toBe('Hlavná 1, Košice')
    expect(c.phone).toBe('+421911111111')
  })
})
