import type { DecisionRecord, RegistryRecord } from "./schema.js";
import { SCHEMA_VERSION } from "./schema.js";
import { digestFiles, gitMetadata, listFiles } from "./repo.js";

interface RegistrySpec {
  id: string;
  type: RegistryRecord["type"];
  name: string;
  purpose: string;
  owner: string;
  sourcePath: string;
  roots: string[];
  dependencies: string[];
  relatedDecisions: string[];
  capabilities: string[];
}

interface DecisionSpec {
  id: string;
  title: string;
  date: string;
  status: DecisionRecord["status"];
  problem: string;
  choice: string;
  rationale: string;
  alternatives?: string[];
  expectedOutcome: string;
  observedOutcome: string;
  reviewAt: string;
  relatedAssets: string[];
  supersedes?: string[];
  confidence?: DecisionRecord["confidence"];
  evidence: Array<{ path: string; line: number; note: string }>;
}

const REGISTRY_SPECS: RegistrySpec[] = [
  {
    id: "brain.engine",
    type: "governance",
    name: "Revolis Brain OS Engine",
    purpose: "Governance, evidence hierarchy, update protocol, and founder gates for company memory.",
    owner: "founder",
    sourcePath: "brain/ENGINE.md",
    roots: ["brain/ENGINE.md"],
    dependencies: ["governance.architecture", "memory.decisions"],
    relatedDecisions: ["rme-dec-20260522-004"],
    capabilities: ["brain-governance", "evidence-hierarchy", "change-gates"],
  },
  {
    id: "governance.architecture",
    type: "documentation",
    name: "Architecture and governance corpus",
    purpose: "Canonical and supporting architecture documents used to constrain product and engineering work.",
    owner: "founder",
    sourcePath: "docs/architecture",
    roots: ["docs/architecture"],
    dependencies: [],
    relatedDecisions: ["rme-dec-20260624-001", "rme-dec-20260623-002"],
    capabilities: ["architecture-guidance", "antipattern-governance", "data-sourcing"],
  },
  {
    id: "memory.decisions",
    type: "decision-log",
    name: "Critical decisions log",
    purpose: "Canonical historical decision source; generated Brain records remain pointers to this log.",
    owner: "founder",
    sourcePath: "memory/decisions.md",
    roots: ["memory/decisions.md", "decisions.md"],
    dependencies: ["governance.architecture"],
    relatedDecisions: ["rme-dec-20260522-004"],
    capabilities: ["decision-history", "rationale-memory", "outcome-tracking"],
  },
  {
    id: "policy.cursor-rules",
    type: "policy",
    name: "Cursor governance rules",
    purpose: "Operational rules referenced as policy evidence, never reclassified as historical decisions.",
    owner: "engineering",
    sourcePath: ".cursor/rules",
    roots: [".cursor/rules"],
    dependencies: ["governance.architecture"],
    relatedDecisions: ["rme-dec-20260611-001", "rme-dec-20260618-001"],
    capabilities: ["coding-policy", "security-policy", "database-policy"],
  },
  {
    id: "repo.packages",
    type: "package",
    name: "Monorepo package manifests",
    purpose: "Workspace topology and direct dependency inventory without copying dependency source code.",
    owner: "engineering",
    sourcePath: "package.json",
    roots: ["package.json", "apps/crm/package.json", "apps/marketing/package.json", "packages"],
    dependencies: ["policy.cursor-rules"],
    relatedDecisions: [],
    capabilities: ["workspace-topology", "dependency-inventory"],
  },
  {
    id: "crm.application",
    type: "application",
    name: "CRM application surface",
    purpose: "Inventory of CRM pages, layouts, and application code used for documentation drift checks.",
    owner: "engineering",
    sourcePath: "apps/crm/src/app",
    roots: ["apps/crm/src/app"],
    dependencies: ["repo.packages", "database.migrations"],
    relatedDecisions: ["rme-dec-20260717-001"],
    capabilities: ["crm-ui", "public-pages", "authenticated-workdesk"],
  },
  {
    id: "crm.api",
    type: "api",
    name: "CRM route handlers",
    purpose: "Inventory of API route handlers used to verify documented endpoint paths.",
    owner: "engineering",
    sourcePath: "apps/crm/src/app/api",
    roots: ["apps/crm/src/app/api"],
    dependencies: ["repo.packages", "database.migrations"],
    relatedDecisions: ["rme-dec-20260522-001", "rme-dec-20260706-001", "rme-dec-20260719-001"],
    capabilities: ["http-api", "integration-contracts", "lead-intake"],
  },
  {
    id: "database.migrations",
    type: "database",
    name: "Supabase migrations",
    purpose: "Versioned database structure used as code-side evidence; production state remains independently verified.",
    owner: "engineering",
    sourcePath: "apps/crm/supabase/migrations",
    roots: ["apps/crm/supabase/migrations"],
    dependencies: ["policy.cursor-rules"],
    relatedDecisions: ["rme-dec-20260624-002", "rme-dec-20260722-001"],
    capabilities: ["database-schema", "tenant-isolation", "consent-storage"],
  },
  {
    id: "ci.workflows",
    type: "workflow",
    name: "GitHub Actions workflows",
    purpose: "CI and governance workflow inventory; remote branch protection is not inferred from files.",
    owner: "engineering",
    sourcePath: ".github/workflows",
    roots: [".github/workflows", ".github/scripts"],
    dependencies: ["repo.packages", "policy.cursor-rules"],
    relatedDecisions: ["rme-dec-20260611-001", "rme-dec-20260618-001", "rme-dec-20260618-002"],
    capabilities: ["continuous-integration", "schema-governance", "merge-policy"],
  },
  {
    id: "automation.n8n",
    type: "automation",
    name: "n8n workflow source area",
    purpose: "Inventory only. Credentials, execution payloads, and customer data are excluded from Brain records.",
    owner: "founder",
    sourcePath: "automation/n8n",
    roots: ["automation/n8n"],
    dependencies: ["policy.cursor-rules"],
    relatedDecisions: [],
    capabilities: ["workflow-automation", "manual-approval-boundary"],
  },
];

const DECISION_SPECS: DecisionSpec[] = [
  {
    id: "rme-dec-20260522-001",
    title: "Standardize the Realvia response contract",
    date: "2026-05-22",
    status: "active",
    problem: "Realvia-facing endpoints returned inconsistent response shapes.",
    choice: "Return a result and message envelope from every Realvia-facing endpoint.",
    rationale: "The integration feedback identified response format as the remaining technical blocker.",
    expectedOutcome: "A stable external response contract for webhook and import calls.",
    observedOutcome: "Implementation is present in the repository; an external partner retest is unavailable.",
    reviewAt: "2026-08-22",
    relatedAssets: ["crm.api"],
    evidence: [
      { path: "memory/decisions.md", line: 90, note: "Canonical decision entry and rationale." },
      { path: "apps/crm/src/lib/realvia/responses.ts", line: 3, note: "Current response helper implementation." },
    ],
  },
  {
    id: "rme-dec-20260522-002",
    title: "Support the Realvia delete v2 payload",
    date: "2026-05-22",
    status: "active",
    problem: "The production delete payload used an action field instead of the legacy deleted boolean.",
    choice: "Recognize action delete and map archiveType to the resulting property status.",
    rationale: "The implementation must follow the documented v2 payload.",
    expectedOutcome: "Correct archival behavior for sold, rented, and cancelled listings.",
    observedOutcome: "The parser implementation is present in the repository.",
    reviewAt: "2027-05-22",
    relatedAssets: ["crm.api"],
    evidence: [
      { path: "memory/decisions.md", line: 95, note: "Canonical decision entry." },
      { path: "apps/crm/src/lib/realvia/types.ts", line: 108, note: "Delete payload guard implementation." },
    ],
  },
  {
    id: "rme-dec-20260522-003",
    title: "Unify Realvia authentication failures",
    date: "2026-05-22",
    status: "active",
    problem: "Missing and incorrect credentials produced different external errors.",
    choice: "Return Invalid authentication for every external authentication failure.",
    rationale: "A stable contract avoids leaking internal detail.",
    expectedOutcome: "Consistent and less revealing authentication errors.",
    observedOutcome: "The shared error constant is present in the repository.",
    reviewAt: "2027-05-22",
    relatedAssets: ["crm.api"],
    evidence: [
      { path: "memory/decisions.md", line: 100, note: "Canonical decision entry." },
      { path: "apps/crm/src/lib/realvia/responses.ts", line: 11, note: "Current shared authentication error." },
    ],
  },
  {
    id: "rme-dec-20260522-004",
    title: "Use repository memory as the AI handoff layer",
    date: "2026-05-22",
    status: "active",
    problem: "Copy and paste handoffs between AI tools caused context drift.",
    choice: "Use the repository memory directory instead of adding Notion or CrewAI.",
    rationale: "Existing versioned files provide a small, inspectable source of truth.",
    expectedOutcome: "Traceable handoffs with less repeated reconstruction.",
    observedOutcome: "The repository contains and actively updates the memory directory.",
    reviewAt: "2026-11-22",
    relatedAssets: ["memory.decisions", "brain.engine"],
    evidence: [{ path: "memory/decisions.md", line: 105, note: "Canonical decision and consequences." }],
  },
  {
    id: "rme-dec-20260611-001",
    title: "Require up-to-date branches before merge",
    date: "2026-06-11",
    status: "verification_required",
    problem: "Parallel stale branches caused repeated semantic regressions.",
    choice: "Require branches to be current and require the Lint, test, build check.",
    rationale: "Semantic conflicts must become visible before merge.",
    expectedOutcome: "Fewer regressions caused by stale verification artifacts.",
    observedOutcome: "The rule is documented locally; remote branch-protection state is unavailable.",
    reviewAt: "2026-07-29",
    relatedAssets: ["ci.workflows", "policy.cursor-rules"],
    evidence: [
      { path: "memory/decisions.md", line: 110, note: "Canonical decision and incident count." },
      { path: ".cursor/rules/l99-golden-rule.mdc", line: 10, note: "Operational policy reference, not a second decision source." },
    ],
  },
  {
    id: "rme-dec-20260618-001",
    title: "Use a pattern-based stealth feature guard",
    date: "2026-06-18",
    status: "active",
    problem: "A name-specific CI guard could be bypassed by renaming forbidden behavior.",
    choice: "Guard the forbidden behavior family with a name pattern.",
    rationale: "Governance must cover behavior rather than one historical label.",
    expectedOutcome: "CI catches renamed variants of the prohibited feature family.",
    observedOutcome: "The pattern is present in repository merge-policy automation.",
    reviewAt: "2026-12-18",
    relatedAssets: ["ci.workflows", "governance.architecture"],
    evidence: [
      { path: "memory/decisions.md", line: 127, note: "Canonical incident and decision." },
      { path: ".github/scripts/automerge-policy.mjs", line: 28, note: "Current policy implementation." },
    ],
  },
  {
    id: "rme-dec-20260618-002",
    title: "Pause the schema guard schedule until secrets exist",
    date: "2026-06-18",
    status: "verification_required",
    problem: "Missing CI secrets caused a false red schema report every night.",
    choice: "Disable the schedule and retain manual workflow dispatch.",
    rationale: "The guard should report schema drift, not configuration noise.",
    expectedOutcome: "No recurring false alarms while manual verification remains available.",
    observedOutcome: "The schedule remains absent from the workflow; remote secret state is unavailable.",
    reviewAt: "2026-07-29",
    relatedAssets: ["ci.workflows"],
    evidence: [
      { path: "memory/decisions.md", line: 133, note: "Canonical decision and re-enable condition." },
      { path: ".github/workflows/schema-governance-guard.yml", line: 3, note: "Current workflow trigger evidence." },
    ],
  },
  {
    id: "rme-dec-20260619-001",
    title: "Show honest pending qualification",
    date: "2026-06-19",
    status: "verification_required",
    problem: "Imported leads lacked the fields needed for readiness scoring.",
    choice: "Show missing qualification instead of fabricating a backfill.",
    rationale: "The available import contains identity, not intent or readiness.",
    expectedOutcome: "Trustworthy UI that does not present invented qualification.",
    observedOutcome: "A current production UI verification is unavailable.",
    reviewAt: "2026-07-29",
    relatedAssets: ["crm.application", "governance.architecture"],
    evidence: [{ path: "memory/decisions.md", line: 140, note: "Canonical fact, veto, and decision." }],
  },
  {
    id: "rme-dec-20260619-002",
    title: "Validate a first-party qualification source",
    date: "2026-06-19",
    status: "superseded",
    problem: "The primary import source did not contain qualification fields.",
    choice: "Inspect a first-party demand export instead of enriching empty fields.",
    rationale: "Qualification must come from an evidenced source.",
    expectedOutcome: "Determine whether a legal bulk qualification source exists.",
    observedOutcome: "The later audit found that the bulk qualification export was unavailable.",
    reviewAt: "2026-06-23",
    relatedAssets: ["governance.architecture"],
    evidence: [
      { path: "memory/decisions.md", line: 145, note: "Original validation decision." },
      { path: "memory/decisions.md", line: 183, note: "Later evidence that superseded the path." },
    ],
  },
  {
    id: "rme-dec-20260622-001",
    title: "Compare every documented property area",
    date: "2026-06-22",
    status: "active",
    problem: "Several truthful area values in one listing produced a false quality flag.",
    choice: "Compare every square-metre value against the structured and source-description area set.",
    rationale: "Quality review must distinguish legitimate multiple area types from drift.",
    expectedOutcome: "Fewer false flags without weakening area validation.",
    observedOutcome: "The decision log records a six-of-six production capability smoke result.",
    reviewAt: "2026-12-22",
    relatedAssets: ["crm.application"],
    evidence: [
      { path: "memory/decisions.md", line: 196, note: "Canonical decision and recorded smoke outcome." },
      { path: "apps/crm/src/lib/capabilities/quality-guardian/review.ts", line: 45, note: "Current review implementation." },
    ],
  },
  {
    id: "rme-dec-20260623-001",
    title: "Reject the low-value client CSV write",
    date: "2026-06-23",
    status: "active",
    problem: "The export was mostly duplicate identity data and did not add qualification.",
    choice: "Do not perform a production write for the marginal broker-assignment field.",
    rationale: "The write risk was not justified by the available new information.",
    expectedOutcome: "Avoid a risky bulk mutation with little customer value.",
    observedOutcome: "The veto is recorded; no separate implementation was required.",
    reviewAt: "2027-06-23",
    relatedAssets: ["database.migrations"],
    evidence: [{ path: "memory/decisions.md", line: 180, note: "Canonical export audit and veto." }],
  },
  {
    id: "rme-dec-20260623-002",
    title: "Remove governance documents hidden in a vague commit",
    date: "2026-06-23",
    status: "active",
    problem: "Unrelated governance documents entered the product repository under a vague commit label.",
    choice: "Remove the documents and require line-level review for docs and chore commits.",
    rationale: "A commit label is not a substitute for scope review.",
    expectedOutcome: "Less documentation contamination and clearer ownership.",
    observedOutcome: "The decision log records the cleanup PR.",
    reviewAt: "2026-12-23",
    relatedAssets: ["governance.architecture", "policy.cursor-rules"],
    evidence: [{ path: "memory/decisions.md", line: 203, note: "Canonical incident, decision, and rule." }],
  },
  {
    id: "rme-dec-20260624-001",
    title: "Define Revolis as a Knowledge Monopoly system",
    date: "2026-06-24",
    status: "active",
    problem: "The product direction was drifting toward generic AI-for-real-estate positioning.",
    choice: "Use the Revenue, Learning, Network, and Evolution loops as the North Star.",
    rationale: "The long-term advantage is accumulated organizational knowledge and outcomes.",
    expectedOutcome: "A durable prioritization frame tied to measurable customer learning.",
    observedOutcome: "The canonical North Star document exists; later-loop outcomes remain unavailable.",
    reviewAt: "2026-09-24",
    relatedAssets: ["governance.architecture"],
    evidence: [
      { path: "memory/decisions.md", line: 218, note: "Canonical decision entry." },
      { path: "docs/architecture/north-star-2027-2030.md", line: 3, note: "Current North Star source." },
    ],
  },
  {
    id: "rme-dec-20260624-002",
    title: "Adopt the prediction and outcome substrate",
    date: "2026-06-24",
    status: "verification_required",
    problem: "Predictions could not be compared with later exclusivity outcomes.",
    choice: "Use decisions and exclusivity outcomes as the Loop 2 substrate, without automatic sending.",
    rationale: "Learning requires both the prediction and its later result.",
    expectedOutcome: "A traceable foundation for future decision-to-outcome evaluation.",
    observedOutcome: "Migration and writer code exist; current production and policy state require verification.",
    reviewAt: "2026-07-29",
    relatedAssets: ["database.migrations", "crm.application"],
    evidence: [
      { path: "memory/decisions.md", line: 224, note: "Canonical decision and safety rule." },
      { path: "apps/crm/supabase/migrations/2026_genome_layer2.sql", line: 4, note: "Repository migration evidence only." },
    ],
  },
  {
    id: "rme-dec-20260624-003",
    title: "Park autonomous genome deployment",
    date: "2026-06-24",
    status: "active",
    problem: "Autonomous deployment lacked sufficient evidence and a proven safety gate.",
    choice: "Keep auto-deploy parked and retain human approval.",
    rationale: "The system must not act autonomously before the quality gate is proven.",
    expectedOutcome: "No unapproved automatic production action.",
    observedOutcome: "The concept remains listed as parked; no unpark decision is recorded.",
    reviewAt: "2026-09-24",
    relatedAssets: ["governance.architecture"],
    evidence: [
      { path: "memory/decisions.md", line: 230, note: "Canonical parking decision." },
      { path: "docs/architecture/l99-parked-concepts.md", line: 12, note: "Current parked-concept evidence." },
    ],
  },
  {
    id: "rme-dec-20260624-004",
    title: "Pivot from architecture writing to revenue-loop execution",
    date: "2026-06-24",
    status: "verification_required",
    problem: "Additional architecture concepts were delaying execution of the first revenue loop.",
    choice: "Close directional architecture and continue with draft-only follow-up execution.",
    rationale: "Customer-facing learning had higher immediate value than another concept document.",
    expectedOutcome: "More execution against Loop 1 and less speculative architecture work.",
    observedOutcome: "A measured outcome for the process decision is unavailable.",
    reviewAt: "2026-07-29",
    relatedAssets: ["governance.architecture"],
    evidence: [{ path: "memory/decisions.md", line: 235, note: "Canonical process decision and merge boundary." }],
  },
  {
    id: "rme-dec-20260706-001",
    title: "Build Proof of Value without a new table",
    date: "2026-07-06",
    status: "active",
    problem: "The product needed a public ROI proof flow without schema duplication.",
    choice: "Reuse the existing SaaS lead store and shared lead creation function.",
    rationale: "Reuse reduced migration risk and preserved one lead contract.",
    expectedOutcome: "A public proof route with honest copy and no new database object.",
    observedOutcome: "The decision log records a merged route and production smoke.",
    reviewAt: "2026-10-06",
    relatedAssets: ["crm.api", "crm.application"],
    evidence: [
      { path: "memory/decisions.md", line: 262, note: "Canonical decision and recorded verification." },
      { path: "apps/crm/src/app/api/proof/route.ts", line: 7, note: "Current API implementation." },
    ],
  },
  {
    id: "rme-dec-20260717-001",
    title: "Use an outcome-first workdesk",
    date: "2026-07-17",
    status: "verification_required",
    problem: "The product emphasized features and fallback KPIs instead of the first customer result.",
    choice: "Use a short first audit, one primary action, and existing signals.",
    rationale: "A smaller path should expose value without creating another AI engine.",
    expectedOutcome: "Faster first value with no fabricated KPI fallback.",
    observedOutcome: "Implementation and verification files exist, but the decision log merge state is stale.",
    reviewAt: "2026-07-29",
    relatedAssets: ["crm.application"],
    evidence: [
      { path: "memory/decisions.md", line: 253, note: "Canonical decision and documented verification." },
      { path: "apps/crm/src/lib/workdesk/first-audit.ts", line: 90, note: "Current first-audit implementation." },
    ],
  },
  {
    id: "rme-dec-20260719-001",
    title: "Gate the valuation widget with deterministic data and privacy",
    date: "2026-07-19",
    status: "verification_required",
    problem: "Customer interest existed, but pricing data, privacy, distribution, and service boundaries were incomplete.",
    choice: "Use a multi-tenant valuation route and prohibit model-generated price ranges without a reproducible source.",
    rationale: "A public estimate must be deterministic, attributable, and privacy-safe.",
    expectedOutcome: "A reusable tenant route without fictitious valuation output.",
    observedOutcome: "The route and deterministic engine exist; current data-license and production gates require verification.",
    reviewAt: "2026-07-29",
    relatedAssets: ["crm.api", "crm.application", "database.migrations"],
    evidence: [
      { path: "memory/decisions.md", line: 241, note: "Canonical scope and gates." },
      { path: "apps/crm/src/app/api/valuation/submit/route.ts", line: 103, note: "Current submission implementation." },
    ],
  },
  {
    id: "rme-dec-20260719-002",
    title: "Bundle valuation in Revolis seat pricing",
    date: "2026-07-19",
    status: "verification_required",
    problem: "The commercial model for the valuation widget was undecided.",
    choice: "Include the widget in the Revolis package instead of charging a separate fee.",
    rationale: "The widget should strengthen the existing seat value proposition.",
    expectedOutcome: "Commercial validation through an additional paying agency.",
    observedOutcome: "Commercial validation is unavailable in repository evidence.",
    reviewAt: "2026-08-19",
    relatedAssets: ["crm.application"],
    evidence: [{ path: "memory/decisions.md", line: 251, note: "Canonical pricing decision and validation condition." }],
  },
  {
    id: "rme-dec-20260722-001",
    title: "Separate sandbox submissions and normalized consent",
    date: "2026-07-22",
    status: "verification_required",
    problem: "A public demo must not create normal production leads or inflate the lead schema with consent fields.",
    choice: "Use a sandbox tenant and a separate lead consent relation.",
    rationale: "The design preserves tenant integrity and keeps consent evidence normalized.",
    expectedOutcome: "Demo submissions remain isolated while consent evidence is versioned.",
    observedOutcome: "Repository code and migration exist; production application and founder smoke are unavailable.",
    reviewAt: "2026-07-29",
    relatedAssets: ["crm.api", "database.migrations"],
    evidence: [
      { path: "memory/decisions.md", line: 172, note: "Canonical decision and founder gate." },
      { path: "apps/crm/supabase/migrations/20260722120000_sandbox_gdpr_consent.sql", line: 108, note: "Repository migration evidence only." },
    ],
  },
];

export function buildRegistry(repoRoot: string): RegistryRecord[] {
  return REGISTRY_SPECS.map((spec) => {
    const files = listFiles(repoRoot, spec.roots);
    const metadata = gitMetadata(repoRoot, spec.sourcePath);
    return {
      schemaVersion: SCHEMA_VERSION,
      id: spec.id,
      type: spec.type,
      name: spec.name,
      purpose: spec.purpose,
      owner: spec.owner,
      status: files.length > 0 ? "active" : "unknown",
      source: { path: spec.sourcePath, commit: metadata.commit },
      createdAt: metadata.createdAt,
      lastVerifiedAt: metadata.lastVerifiedAt,
      dependencies: [...spec.dependencies].sort(),
      relatedDecisions: [...spec.relatedDecisions].sort(),
      evidence: [
        {
          path: spec.sourcePath,
          commit: metadata.commit,
          note: files.length > 0
            ? `Inventory contains ${files.length} file(s); digest ${digestFiles(repoRoot, files)}.`
            : "Source unavailable in the current workspace.",
        },
      ],
      confidence: files.length > 0 ? "high" : "low",
      sensitivity: "internal",
      capabilities: [...spec.capabilities].sort(),
      inventory: {
        fileCount: files.length,
        digest: files.length > 0 ? digestFiles(repoRoot, files) : "unavailable",
        sample: files.slice(0, 12),
      },
      canonical: false,
    } satisfies RegistryRecord;
  }).sort((left, right) => left.id.localeCompare(right.id));
}

export function buildDecisions(repoRoot: string): DecisionRecord[] {
  return DECISION_SPECS.map((spec) => {
    const source = spec.evidence[0].path;
    const sourceMeta = gitMetadata(repoRoot, source);
    return {
      schemaVersion: SCHEMA_VERSION,
      id: spec.id,
      title: spec.title,
      date: spec.date,
      owner: "founder",
      status: spec.status,
      problem: spec.problem,
      choice: spec.choice,
      rationale: spec.rationale,
      alternatives: spec.alternatives ?? ["unavailable"],
      expectedOutcome: spec.expectedOutcome,
      observedOutcome: spec.observedOutcome,
      reviewAt: spec.reviewAt,
      relatedAssets: [...spec.relatedAssets].sort(),
      supersedes: [...(spec.supersedes ?? [])].sort(),
      source: { path: source, commit: sourceMeta.commit },
      evidence: spec.evidence.map((item) => {
        const metadata = gitMetadata(repoRoot, item.path);
        return { ...item, commit: metadata.commit };
      }),
      confidence: spec.confidence ?? "high",
      sensitivity: "internal",
      canonical: false,
    } satisfies DecisionRecord;
  }).sort((left, right) => left.id.localeCompare(right.id));
}
